alias аллобялть='echo шо'
alias когда='echo завтра.'
alias м='echo м'
alias chown='chown -v'
alias cls='clear'
alias cp='cp -vr'
alias diff='diff --color=auto'
alias gay='yay'
alias lA='ls -lA'
alias la='ls -la'
alias lh='ls -lh'
alias lhA='lA -h'
alias lha='la -h'
alias ll='ls -l'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias mv='mv -v'
alias neofetch='pridefetch -f trans'
alias rm='rm -vr'
alias rmdir='rmdir -v'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias whoami='echo "I'\''m Travis. Travis Scott"'
