alias аллобялть='echo шо'
alias когда='echo завтра.'
alias м='echo м'
alias cls='clear'
alias cp='cp -v'
alias diff='diff --color=auto'
alias gay='yay'
alias l='ls -l'
alias lh='ls -lhA'
alias ll='ls -la'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias mv='mv -v'
alias neofetch='pridefetch -f trans'
alias rm='rm -v'
alias rmdir='rmdir -v'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias whoami='echo "I'\''m Travis. Travis Scott"'
