alias аллобялть='echo шо'
alias когда='echo завтра.'
alias м='echo м'
alias ..='cd ..'
alias gcc='gcc -Wall'
alias grep='grep -r'
alias chown='chown -v'
alias cls='clear'
alias cp='cp -vr'
alias diff='diff --color=auto'
alias gay='yes | yay'
alias lA='ls -lA'
alias la='ls -la'
alias lh='ls -lh'
alias lhA='lA -h'
alias lha='la -h'
alias ll='ls -l'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias mv='mv -v'
alias neofetch='pridefetch -f ukrainian'
alias rm='rm -vr'
alias rmdir='rmdir -v'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias wget='wget -rnd'
alias whoami='echo "I'\''m Travis. Travis Scott"'
alias yt-audio='\youtube-dl -x --audio-quality=0 --audio-format=mp3'
alias youtube-dl='youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio --merge-output-format mp4'
alias zip='zip -r'
